### ISSUE TITLE
[Feature Request] Expose Alarm Devices of Ring

### ISSUE THREAD

**Issue by thomaswitt** [daneedk/com.amazon.ring#10]
The [Homebridge Ring Plug-In](https://github.com/dgreif/ring/tree/main/packages/homebridge-ring) also supports the Ring Alarm devices. It would be great if the Homey Plug-in would also support this. Especially helpful would be:

- Current Alarm Status (alarming yes/no)
- Movement sensors, Contact Sensors and Glassbreaking Sensors, … as Homey Sensors

Especially the movement sensors would be helpful because one could also integrate them as regular sensors to automatically turn the light on/off when somebody is at home.

**Comment by daneedk** [comment]
Hi Thomas,
I have no plans to expose devices from the Ring Security line to Homey, my time is to limited for that.

Thanks,

Danee
