### ISSUE TITLE
Create snapshot from Ring Video doorbell

### ISSUE THREAD

**Issue by LesPaul1962** [daneedk/com.amazon.ring#11]
Previous I had a Doorbird (which broke) and it was possible to catch a snapshot when the doorbell was pushed. Is this also possible for the Ring Video Doorbell?

**Comment by daneedk** [comment]
That’s sure possible, please see https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364
Support on the app is given there as Github is mainly used for bug tracking.
