### ISSUE TITLE
Error condition alarm_motion

### ISSUE THREAD

**Issue by DaWa74** [daneedk/com.amazon.ring#15]
Hi daneedk
I get the error below, while AND-condition of motion of Ring Cam
Motion is set activ in device and device show the motion with yellow !
Error:
Flow Card not registered (type: condition, id: alarm_motion)
a mistake on my side or an error?
Ring App V2.11.0, Homey Pro 11.0.0
regards Daniel

![image](https://github.com/daneedk/com.amazon.ring/assets/88822495/c63f8109-150c-4d07-899b-046ed02cf755)

**Comment by DaWa74** [comment]
Hello Danee,Thank you very much for your response.You don’t need to hurry upI just wanted to report the issue.Thank you for investing your time in the app.Regards DaniVon meinem iPhone gesendetAm 26.04.2024 um 19:31 schrieb Danee ***@***.***>:﻿
Hi @DaWa74,
I've never seen this before, but when I create a test flow I see the same behaviour. alarm_motion is a standard capability and in the past it wasn't needed to add code to make flowcards work.
When I create code to actually check the condition and provide it to the flowcars it works, so it's fixable, but before I publish this I want to check out why this behaviour is changed.
Cheers,
Danee

**Comment by daneedk** [comment]
This should be fixed in 2.11.1 which I released earlier, I forgot to update this issue, sorry about that.

Can you please check if this is working  for you?

**Comment by DaWa74** [comment]
Hi Danee
I can‘t choose the and-condition, it‘s not avaible
Regards Dani

**Comment by daneedk** [comment]
Ok, strange, what app version are you using?

**Comment by DaWa74** [comment]
v2.11.1
Do you have the card?

**Comment by daneedk** [comment]
Yes, same version. 
what type of camera/doorbell is it?
