### ISSUE TITLE
Ring camera app for homey does not use tags

### ISSUE THREAD

**Issue by douwevt** [daneedk/com.amazon.ring#16]
I have the Ring app installed on my homey, but a rather simple flow using the tags, does not work.
![image](https://github.com/daneedk/com.amazon.ring/assets/10944424/f517b01a-cfef-46b1-ac00-05ba9f0bf7bf)
regards,
Douwe van Terwisga

**Comment by daneedk** [comment]
This functionality requires a Ring Subscription and a Camera that supports this feature, do you have both?

**Comment by douwevt** [comment]
Well I have the subscription and I thought the camera had that feature. It is a stick up cam plug-in 3rd generation

**Comment by daneedk** [comment]
Ok, that's great. 
Could you check the Smart Alerts settings of the device in the official Ring app?

**Comment by douwevt** [comment]
You mean these?
![IMG_6324](https://github.com/daneedk/com.amazon.ring/assets/10944424/c181ff6c-b342-4345-afb4-33dd2a6fdc46)

**Comment by daneedk** [comment]
Ok, it looks like al conditions are met, it should work.

Could you please creat a flow like below and see what is written to the timeline?

<img width="922" alt="image" src="https://github.com/daneedk/com.amazon.ring/assets/16610696/bc8e2ea8-7e23-47e1-9f32-8fab5736c787">

**Comment by douwevt** [comment]
That works....
![image](https://github.com/daneedk/com.amazon.ring/assets/10944424/9d1909f0-d08c-4fc7-a961-97cd1ab5fc15)
It also recognizes "other".....

**Comment by daneedk** [comment]
Ok, so it must be a problem with the logic card as the tag contains the actual detected motion type, the logic card is part of the Homey firmware and beyond the influence of this app.

Could you please check there's no leading or trailing space in the condition card?

If that's not the case I suggest making a post on the [Homey Community Forum](https://community.homey.app) perhaps others have seen this behaviour before on the logic card and have a solution for you.

**Comment by douwevt** [comment]
Thanks Daneedk, I have recreated the flow, and now it seems to work, so indeed perhaps some leading spaces or so. Thank you for your efforts!

**Comment by daneedk** [comment]
Great, I’ll close this issue.
