### ISSUE TITLE
Motion Alarm and Doorbell not working.

### ISSUE THREAD

**Issue by Genghes** [daneedk/com.amazon.ring#18]
Ever since the update to 2.11.17 about two days ago the motion alarm and doorbell does not work.
It is not triggering in the app.

I tried to repair but no change.
I do get a snapshot so it communicates fine with the api.

![image](https://github.com/user-attachments/assets/82b75751-8482-4351-8c05-4edc29f3c065)

**Comment by daneedk** [comment]
Hi, 
Please see the forum topic: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364

You’ll have to remove the authorized devices in your Ring account and reauthenticate in the homey app, please follow these instructions: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364/5
