### ISSUE TITLE
No notification when movement at doorbell received in homey

### ISSUE THREAD

**Issue by dbuekenh** [daneedk/com.amazon.ring#19]
Hi,

I al using for years your app to connect 3 ring devices in homey. Sinse the last months it seams that i am not receiving any notifications from my doorbell in homey. If someone rings, that is working fine.

Here you see the flows that i have enabled for my doorbell. You can see the 3 flows for the action if movement is detected. But as said they are not triggered anymore.

![image](https://github.com/user-attachments/assets/2cfe0fa8-0808-4397-a86c-25b120cc5024)

I am using a homey pro 2023 amwith the lastest software. For the ring app i am using version V2.11.17

Many thanks for your time and wishing you an family a healthy 2025!

Kind regards 
Dirk

**Comment by daneedk** [comment]
Hi Dirk,

Ring made a change to their API, please see this post on how to fix: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364/5

A lot more information on this can also be found in that topic.

Best wishes to you too for the new year ahead!

Cheers,

Danee

**Comment by dbuekenh** [comment]
Hi Danee,Thanks for your help!Kind regardsDirkVerstuurd vanaf mijn iPhoneOp 31 dec 2024 om 13:05 heeft Danee ***@***.***> het volgende geschreven:﻿
Hi Dirk,
Ring made a change to their API, please see this post on how to fix: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364/5
A lot more information on this can also be found in that topic.
Best wishes to you too for the new year ahead!
Cheers,
Danee
