### ISSUE TITLE
Authenticaton fails

### ISSUE THREAD

**Issue by geirnar** [daneedk/com.amazon.ring#3]
I signed up for Ring yesterday and stored the credentials in password manager. I have logged into Ring with it several times, but it is not accepted by the app. MFA is set up for my account. I’m using Homey 2023.

**Comment by geirnar** [comment]
![19E635DA-FC40-4EF2-B28D-F14E7B472CE8](https://user-images.githubusercontent.com/35507286/229882258-afbcf883-806a-4e23-a162-05bf0ae21b89.jpeg)

**Comment by daneedk** [comment]
Hi @geirnar 
This error is given when you can't be authenticated at Ring with the given username and password. Yesterday evening there were some serious issues at Ring, especially with authentication. These problems seems to be fixed, the Ring app on my 3 Homeys started functioning again overnight.

Could you please stop the Ring App, start it again and next try to authenticate at Ring again? If it works it works, if it doesn't work please send me a Diagnostics Report from the app.

**Comment by geirnar** [comment]
I’m unfortunately still not able to authenticate, despite restart of app, deleting app + restarting Homey + reinstalling app. I have also re-logged in to Ring to check credentials, and switched from SMS to Authenticator at MFA method. No success still.

**Comment by daneedk** [comment]
Could you please stop the app, start it, wait a bit and next try to logon. When it fails again, please send a Diagnostics Report from the app.

**Comment by geirnar** [comment]
Just did. See log with reference e2d7864b-bf9d-4799-a930-7c45dc3b7ae2

**Comment by daneedk** [comment]
The log shows Ring returns an authentication error on your credentials. 

- Are there any special characters in your username or password?
- Can you try adding a device and authentication on https://my.homey.app on a computer?

**Comment by geirnar** [comment]
Thank you, that was the explanation, as it included the Norwegian character æ.This is included in ISO 8859-1, and is accepted by Ring, but not when added through the app. It now worked after changing the password.
