### ISSUE TITLE
Motion alarm flow not working

### ISSUE THREAD

**Issue by Pjotrvanmourik** [daneedk/com.amazon.ring#5]
Since last week my flow to send a message when the motion alarm is activated is not working.
I think the pulse of the status to be active is to short for the flow to detect.

**Comment by daneedk** [comment]
Hi Pjotr,

Ring made a change to the way the API works in the beginning of may which causes this behaviour. I’v published a new version that does not completely fix it but does mak the impact of the change smaller: https://community.homey.app/t/ring-doorbell-and-camera-support-for-homey/76364/152

I hope a permanent fix will be available soon, please keep an eye on that forum topic to keep informed
