### ISSUE TITLE
Merge the two app and support api control

### ISSUE THREAD

**Issue by Julien-Martin** [daneedk/com.amazon.ring#7]
Hi, wouldn't it be interesting to merge the two applications and allow device support (Contact Sensor, Keypad, base station) with API instead of Z-Wave ?

My whole house is ring protected, and i want to continue using their apps.

Maybe it's possible to use both Base Station and Z-Wave network throught Homey ? 🤔

**Comment by daneedk** [comment]
Hi Julien,

I’ve looked into that, and understand why you would want that but it is a lot of work with little to no benefit for myself so I’ve decided to spend no time on it.

Cheers,

Danee
